### ISSUE TITLE
Phpmyadmin not running

### ISSUE THREAD

**Issue by Futureganteng** [r3c/winp#18]
Hello, sorry for opening the first issue

I was using your application, the mariadb, nginx, and the php was going well, i have an issue on the phpmyadmin when the mariadb, nginx and php was running, the phpmyadmin stay ready (not running), i accessed on browser the /phpmyadmin it keep returning a 404 not found, im confused should i configure the phpmyadmin manually?

**Comment by r3c** [comment]
Hello! Indeed phpmyadmin stays in "ready" mode because it's not really a running process like the other ones but just a website being copied locally and ready to be served. Maybe that's a bit confusing/technical and I should change it to "running" like the other ones 🙂

However it's supposed to respond when accessing URL http://127.0.0.1/phpmyadmin/ in your browser:

![image](https://github.com/r3c/winp/assets/979446/ad5561bf-b3ff-4f16-b733-4a030b15d703)

If this doesn't work, would you please mind sharing the contents of file `nginx\1.19.9\conf\nginx.conf` located in your install directory (the one you specified in configuration, by default it's a "Install" directory located inside the folder you unzipped Winp into)?

**Comment by r3c** [comment]
I reviewed your configuration file and it seems perfectly fine. It could have been the port 80 being used by another instance of nginx indeed, but since the version number matches the one used by Winp that would be quite a coincidence! Do you see anything wrong in Nginx's "error.log" file within its log directory?

**Comment by r3c** [comment]
Oh great, I'm glad it works for you! Even though it's a bit surprizing as phpMyAdmin is supposed to be configured through its own special type ("Use phpmyadmin" in configuration) so it can be served through Install directory instead of Root. Maybe something is causing the location directive to be ignored in your setup, I'll try to investigate this and update here if I find anything.

Thanks for the update!

**Comment by r3c** [comment]
Hello again @Futureganteng, FYI I just released version [0.3.1](https://github.com/r3c/winp/releases/tag/0.3.1) that addresses the issue you mentioned earlier about ready vs running packages. I also tried to reproduce your issue but didn't manage to. However another question occurred to me: did you try to access phpMyAdmin using `http://localhost/phpmyadmin/` (with a trailing slash) or `http://localhost/phpmyadmin`? Only the former is expected to work with shipped nginx configuration.

**Comment by r3c** [comment]
Oh, that was my only remaining lead 😅 I tried reproducing and had another look at the log & config file you sent but don't see anything wrong. phpMyAdmin is served from the install directory in all the configurations I tried. I'll setup Winp on different machines & OSes trying to reproduce, but was unlucky so far. Sorry about this!
